### ISSUE TITLE
bounces = NO?

### ISSUE THREAD

**Issue by KimDarren** [uzysjung/UzysAnimatedGifLoadMore#2]
bounces값이 NO인 UITableView에서 라이브러리를 사용할 수 있는 방법이 있나요?

**Comment by uzysjung** [comment]
이해를 잘 못하겠네요. scrollview면 다 될텐데요...

**Comment by KimDarren** [comment]
@uzysjung 안녕하세요. tableView의 bounces 값을 NO로 주면 작동을 안하더라구요.. 혹시 bounes 값을 NO로 주고 사용할 수 있는 방법이 있을까 해서 이슈를 열었습니다.

**Comment by uzysjung** [comment]
bounce가 no 이면서 되길 원하시면 커스터마이제이션을 하셔야 될 것 같습니다. UITapGesturerecognizer를 view에 붙이셔서 scrollview가 끝에까지 내려간 상태에서 터치를 위로 올리는 것을 체크하셔 트리거링되도록 수정하시면 되겠네요. activity view가 view controller view 에서 최상위에 있어야겠지요 그 뷰가 tap 제스쳐를 보고 위로 올라오는 거니까요

**Comment by KimDarren** [comment]
@uzysjung 답변 감사합니다!! 많은 도움이 되었어요 :)
