### ISSUE TITLE
Load more not called when first time

### ISSUE THREAD

**Issue by hardikdevios** [uzysjung/UzysAnimatedGifLoadMore#5]
Ok well everything is working fine thanks for this great Lib,
The issue which is happening right now is when you first load and then scroll and Drag the Tableview from bottom it wont call first time after you stop dragging and start dragging again everything works fine.
This issue is happening only first time when tableview load new Cells  after that load more works fine with normal dragging, have you find anything similar to this ?

**Comment by uzysjung** [comment]
Hi I tested on my example. I couldn't find the issue.
