### ISSUE TITLE
Error when building project

### ISSUE THREAD

**Issue by NikKovIos** [uzysjung/UzysAnimatedGifLoadMore#7]
clang: error: no such file or directory: '/Users/nikkov/Downloads/UzysAnimatedGifLoadMore-master/UzysAnimatedGifLoadMore/Pods/Target Support Files/AnimatedGIFImageSerialization/AnimatedGIFImageSerialization-dummy.m'
clang: error: no input files

**Comment by uzysjung** [comment]
Plz check new version
